### ISSUE TITLE
'One or more errors occurred' on updating View Model properties

### ISSUE THREAD

**Issue by NOHJ-1** [NeutroniumCore/Neutronium#108]
I am developing a data editor but I am having exceptions on updating the view model:

```
DataContentCreator.exe Error: 0 : Neutronium - Error: WebView crashed trying recover
DataContentCreator.exe Information: 0 : Neutronium - Info: Loaded: /View/dist/index.html
DataContentCreator.exe Information: 0 : Neutronium - Info: Loaded: /View/dist/css/app.css
DataContentCreator.exe Information: 0 : Neutronium - Info: Loaded: /View/dist/js/app.js
DataContentCreator.exe Information: 0 : Neutronium - Info: Loaded: /View/dist/js/chunk-vendors.js
DataContentCreator.exe Information: 0 : Neutronium - Info: Loaded: /View/dist/css/chunk-vendors.css
The thread 0x3a00 has exited with code 0 (0x0).
DataContentCreator.exe Information: 0 : Neutronium - Info: Exception encountered during task dispatch: Chromium.CfxRemotingException: Remote connection lost. ---> System.IO.EndOfStreamException: Unexpected end of stream.
   at Chromium.Remote.StreamHandler.FillReadBuffer(Int32 count)
   at Chromium.Remote.RemoteConnection.ReadLoop()
   at Chromium.Remote.RemoteConnection.ReadLoopEntry()
   --- End of inner exception stack trace ---
   at Chromium.Remote.RemoteCall.RequestExecution(RemoteConnection connection)
   at Chromium.Remote.CfrV8Value.CreateUndefined()
   at Neutronium.WebBrowserEngine.ChromiumFx.V8Object.ChromiumFXJavascriptRoot.Invoke(String functionName, IWebView context, IJavascriptObject[] parameters)
   at Neutronium.JavascriptFramework.Vue.VueJavascriptSessionInjector.RegisterMainViewModel(IJavascriptObject jsObject)
   at Neutronium.Core.Binding.BidirectionalMapper.RegisterMain(IJavascriptObject res)
   at Neutronium.WebBrowserEngine.ChromiumFx.EngineBinding.ChromiumFxDispatcher.<>c__DisplayClass15_0`1.<ToTaskAction>g__Result|0()
DataContentCreator.exe Information: 0 : Neutronium - Info: Problem in exiting chromiumFx context : Chromium.CfxRemotingException: Remote connection lost. ---> System.IO.EndOfStreamException: Unexpected end of stream.
   at Chromium.Remote.StreamHandler.FillReadBuffer(Int32 count)
   at Chromium.Remote.RemoteConnection.ReadLoop()
   at Chromium.Remote.RemoteConnection.ReadLoopEntry()
   --- End of inner exception stack trace ---
   at Chromium.Remote.RemoteCall.RequestExecution(RemoteConnection connection)
   at Chromium.Remote.CfrV8Context.Exit()
   at Neutronium.WebBrowserEngine.ChromiumFx.EngineBinding.ChromiumFxDispatcher.ChromiumFxContext.Dispose()
Neutronium - Browser Log: Message: Neutronium: ViewModel injected, source: , line number: 8699, page: https://application/View/dist/index.html#/main
An unhandled exception of type 'System.AggregateException' occurred in mscorlib.dll
One or more errors occurred.
```

My cjson looks like this when I have yet to load a file to edit (this based from the Neutronium SPA Template, nothing much has been changed):
```
{
    "ViewModel": {
        "ApplicationInformation": {
            "MadeBy": "Nohj",
            "Name": "Data Content Creator",
            "Version": "1.0.0.0",
            "Year": 2019
        },
        "CurrentViewModel": {},
        "Editor": {
            "CurrentlySelectedTreeItem": null,
            "Session": null,
            "SingleItemCollection": null
        },
        "Modal": null,
        "Notification": null,
        "Router": {
            "AfterResolveCommand": "cmd(true)",
            "BeforeResolveCommand": "cmd(true)",
            "Route": "main"
        },
        "Window": {
            "Close": "cmd(true)",
            "Maximize": "cmd(true)",
            "Minimize": "cmd(true)",
            "Normalize": "cmd(true)",
            "State": {
                "type": "WindowState",
                "intValue": 0,
                "name": "Normal",
                "displayName": "Normal"
            }
        }
    },
    "Window": {
        "CloseReady": "cmd(true)",
        "EndOpen": "cmd(true)",
        "IsListeningClose": false,
        "IsListeningOpen": false,
        "State": {
            "type": "WindowLogicalState",
            "intValue": 1,
            "name": "Opened",
            "displayName": "Opened"
        }
    },
    "version": 1
}
```

I am trying to update the properties on this part, specifically the 'Session' part:
```
"Editor": {
            "CurrentlySelectedTreeItem": null,
            "Session": null,
            "SingleItemCollection": null
        },
```

but then that error occurs. How I update them looks like this. (the SetValue are my helpers, they do the INotifyPropertyChanged upon setting)

```
public SessionViewModel Session
        {
            get => _session;
            set
            {
                if(SetValue(ref _session, value))
                    SingleItemCollection = new ObservableCollection<SessionViewModel> { _session };
            }
        }

        public ObservableCollection<SessionViewModel> SingleItemCollection
        {
            get => _singleItemCollection;
            set => SetValue(ref _singleItemCollection, value);
        }

        public object CurrentlySelectedTreeItem
        {
            get => _currentlySelectedTreeItem;
            set => SetValue(ref _currentlySelectedTreeItem, value);
        }
```

I tried disposing the HTMLViewControl before updating then re instantiating and setting the properties like how it ought to be as it was on initialization but then a somewhat same error occurs
```
           HTMLViewCtrl.Dispose();
           HTMLViewCtrlContainer.Children.Remove(HTMLViewCtrl);

            /*  Instantiates */
            ViewModel.Session = new SessionViewModel(data);

            Dispatcher.DispatchOnContextIdle(() =>
            {
                HTMLViewCtrl = new HTMLViewControl();
                HTMLViewCtrlContainer.Children.Add(HTMLViewCtrl);

                Dispatcher.DispatchAfterRender(() =>
                {
                    HTMLViewCtrlContainer.InvalidateVisual();

                    HTMLViewCtrl.Uri = SetUp.Uri;
                    HTMLViewCtrl.DebugCommands = SetUp.DebugCommands;
                    HTMLViewCtrl.IsDebug = SetUp.Debug;
                });
            });
```

```
DataContentCreator.exe Information: 0 : Neutronium - Info: Loaded: /View/dist/index.html
DataContentCreator.exe Information: 0 : Neutronium - Info: Loaded: /View/dist/css/app.css
DataContentCreator.exe Information: 0 : Neutronium - Info: Loaded: /View/dist/js/app.js
DataContentCreator.exe Information: 0 : Neutronium - Info: Loaded: /View/dist/js/chunk-vendors.js
DataContentCreator.exe Information: 0 : Neutronium - Info: Loaded: /View/dist/css/chunk-vendors.css
The thread 0x326c has exited with code 0 (0x0).
DataContentCreator.exe Information: 0 : Neutronium - Info: Exception encountered during task dispatch: Chromium.CfxRemotingException: Remote connection lost. ---> System.IO.EndOfStreamException: Unexpected end of stream.
   at Chromium.Remote.StreamHandler.FillReadBuffer(Int32 count)
   at Chromium.Remote.RemoteConnection.ReadLoop()
   at Chromium.Remote.RemoteConnection.ReadLoopEntry()
   --- End of inner exception stack trace ---
   at Chromium.Remote.RemoteCall.RequestExecution(RemoteConnection connection)
   at Chromium.Remote.CfrV8Value.CreateUndefined()
   at Neutronium.WebBrowserEngine.ChromiumFx.V8Object.ChromiumFXJavascriptRoot.Invoke(String functionName, IWebView context, IJavascriptObject[] parameters)
   at Neutronium.JavascriptFramework.Vue.VueJavascriptSessionInjector.RegisterMainViewModel(IJavascriptObject jsObject)
   at Neutronium.Core.Binding.BidirectionalMapper.RegisterMain(IJavascriptObject res)
   at Neutronium.WebBrowserEngine.ChromiumFx.EngineBinding.ChromiumFxDispatcher.<>c__DisplayClass15_0`1.<ToTaskAction>g__Result|0()
DataContentCreator.exe Information: 0 : Neutronium - Info: Exception encountered during task dispatch: Chromium.CfxRemotingException: Remote connection lost. ---> System.IO.EndOfStreamException: Unexpected end of stream.
   at Chromium.Remote.StreamHandler.FillReadBuffer(Int32 count)
   at Chromium.Remote.RemoteConnection.ReadLoop()
   at Chromium.Remote.RemoteConnection.ReadLoopEntry()
   --- End of inner exception stack trace ---
   at Chromium.Remote.RemoteCall.RequestExecution(RemoteConnection connection)
   at Chromium.Remote.CfrV8Value.CreateInt(Int32 value)
   at Neutronium.WebBrowserEngine.ChromiumFx.EngineBinding.ChromiumFxFactory.CreateObjects(ObjectsCreationOption option)
   at Neutronium.Core.Binding.Builder.JavascriptObjectBulkBuilder.BulkCreateObjects()
   at Neutronium.Core.Binding.Builder.JavascriptObjectBulkBuilder.CreateObjects()
   at Neutronium.Core.Binding.Builder.JavascriptObjectBulkBuilder.UpdateJavascriptValue()
   at Neutronium.Core.Binding.Updaters.JsUpdateHelper.UpdateOnJavascriptContext(BridgeUpdater updater, IJsCsGlue value)
   at Neutronium.WebBrowserEngine.ChromiumFx.EngineBinding.ChromiumFxDispatcher.CfrTask_Execute(Object sender, CfrEventArgs e)
DataContentCreator.exe Information: 0 : An unhandled exception of type 'System.AggregateException' occurred in mscorlib.dll
One or more errors occurred.
```

**Comment by David-Desmaisons** [comment]
> I tried disposing the HTMLViewControl before updating then re instantiating and setting the properties like how it ought to be as it was on initialization but then a somewhat same error occurs

This won't work! Dispose the control only when you close the window.

It is not clear when this problem is hapening. Could you clarify?
Does the application open correctly?
Is this expection is raised when you call: `ViewModel.Session = new SessionViewModel(data);`?

If so, could you share the code and the wholes traces, since the application start?

**Comment by David-Desmaisons** [comment]
Check when you are disposing the HTMLViewControl  and make sure, you are not doing it during the application lifecycle. It is done once in the template when application close.

**Comment by David-Desmaisons** [comment]
`--- Updating the session property...`
What is trigerring this update? Do you fave a callstack?
Is this happening in the UI thread?

**Comment by David-Desmaisons** [comment]
And also:
> I tried removing the the notification on setting the Session property, and no error happened.
Could you clarify what do you mean by notification?

**Comment by NOHJ-1** [comment]
`--- Updating the session property...`
That's when the `ViewModel.Session` is being changed. For debugging purposes

> I tried removing the the notification on setting the Session property, and no error happened.
The INotifyPropertyChanged.

**Comment by David-Desmaisons** [comment]
```
--- Updating the session property...
That's when the ViewModel.Session is being changed. For debugging purposes
```
Still with this information I do not have any clue of what is trigerring the update:
Is it callback?  
Is it an event callback?
Could you share the callstack of  thta trigers the property updates?
These information are crucial for me to be abble to help you.
Another possibility is to provide an access to the reo where this problem ahppens.

**Comment by David-Desmaisons** [comment]
> --- Updating the session property...
> That's when the ViewModel.Session is being changed. For debugging purposes

Does this mean tha you are trigerring the update from the debugger?

**Comment by NOHJ-1** [comment]
I really thank you for your time in trying to help me. 

wait wait.

The Session property is being changed from a callback.

`--- Updating the session property...`
That's just a `System.Console.WriteLine();` before the `ViewModel.Session = new SessionViewModel(data);` fires.

About the callstack, I can't show any since:
```
Your app has entered a break state, but there is no code to show because all threads were executing external code (typically system or framework code).
```

[Debug Output of it happening, take note of where the '--- Updating the session property...' is, since that's where the Session property is going to be changed, then ends on '--- [END] Updating the session property...'](https://github.com/NeutroniumCore/Neutronium/issues/108#issuecomment-475122899)

**Comment by NOHJ-1** [comment]
i'll try to create a mockup project of this since I can't just upload this project

**Comment by NOHJ-1** [comment]
try catching the ViewModel.Session = new SessionViewModel(data); doesn't even help

**Comment by David-Desmaisons** [comment]
Ok, I will wait for the mock-up.

Meanwhile
> The Session property is being changed from a callback.
Could you explain better?

**Comment by NOHJ-1** [comment]
The user clicks a button. Then a file dialog shows up, prompting to select a file (JSON). If successful, then loads the contents from the file, and then--where it crashes, it updates the UI.

I've been really busy these weekends.

**Comment by David-Desmaisons** [comment]
Could you share the callstack leading to the update of the ViewModel.Session?

**Comment by NOHJ-1** [comment]
I think I have an idea on why the error is happening. 
It's probably with the data types or the objects within the Session object being loaded. Since when I added Bindable(false) to all the properties that I did not need, it crashed no more.

I'm going to try to pinpoint which property/data_type was making the app crash to help improving the Neutronium

**Comment by NOHJ-1** [comment]
I somehow can't pinpoint exactly what was causing it. 

I think it's with the objects having children which are referencing their parent objects. It's kinda of a flaw on my part. 

But the crashing does not seem to happen all the time, so I'm not sure if it was that one. Maybe you have an idea on this 'objects with children referencing back their parents' thing

**Comment by David-Desmaisons** [comment]
Neutronium supports circular references without restriction.

Your scenario migth be linked with having the class Type used as some point as a ViewModel, The main problem is that Type exposes many property that will throw exceptions resulting in a very degraded performance, that may lead to this crash.

Using debug or release build result in a dramatic performance changes when dealing with this kind of scenarios, so that migth explain the fact that the crash is not reproducible.

**Comment by NOHJ-1** [comment]
> The main problem is that Type exposes many property that will throw exceptions resulting in a very degraded performance, that may lead to this crash

ok, well I think that's that. Thanks for the help!
