### ISSUE TITLE
Neutronium.Core.Exceptions.NeutroniumException: 'Not able to find WebEngine '

### ISSUE THREAD

**Issue by wwestlake** [NeutroniumCore/Neutronium#111]
I have a WPF application (not a starter app, a real one that is quite complex.)  I want to add a web browser and have selected this.  My view loads but throwns the below execption.  

the view contains only         <neut:HTMLViewControl Uri="{Binding Address}" />

I don't know what is happening here, I am sure I have everything installed.

'''
Neutronium.Core.Exceptions.NeutroniumException
  HResult=0x80131500
  Message=Not able to find WebEngine 
  Source=Neutronium.WPF
  StackTrace:
   at Neutronium.WPF.Internal.HTMLControlBase.Init()
   at Neutronium.WPF.Internal.HTMLControlBase.<NavigateAsyncBase>d__88.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Neutronium.WPF.HTMLViewControl.<CheckNavigation>d__18.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Neutronium.WPF.HTMLViewControl.<OnUriChanged>d__17.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at UBT.FaultSense.Startup.Program.Main(String[] args) in G:\source\repos\UBT.FaultSense\UBT.FaultSense.UI\Program.cs:line 53
'''

**Comment by David-Desmaisons** [comment]
Check this referemce:
https://neutroniumcore.github.io/Neutronium/articles/installing.html#for-an-existing-wpf-project

You should register ChromiumFx webengine and vue binder when the application is starting.

**Comment by wwestlake** [comment]
Yes I found that once I got home from work having spent most of the day trying to figure it out.  I will close this, thanks :)
