### ISSUE TITLE
glueHelper not found

### ISSUE THREAD

**Issue by jmecosta** [NeutroniumCore/Neutronium#16]
@David-Desmaisons hi

im keeping getting a this

NeutroniumException: glueHelper not found!

   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Neutronium.Core.Navigation.DoubleBrowserNavigator.Switch(Task`1 binding, HTMLLogicWindow window, TaskCompletionSource`1 tcs)
   at Neutronium.Core.Navigation.DoubleBrowserNavigator.<>c__DisplayClass34_0.<Navigate>b__2(Task`1 t)
   at Neutronium.Core.Infra.TaskHelper.<>c__DisplayClass1_0`1.<WaitWith>b__0(Task[] ts)
   at System.Threading.Tasks.TaskFactory`1.<>c.<ContinueWhenAllImpl>b__57_1(Task`1 completedTasks, Object state)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Neutronium.Core.Navigation.DoubleBrowserNavigator.<>c__DisplayClass34_0.<<Navigate>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)

do you have any ideas why? 

ive started using some html with some redirection to saml authetication server. but there is no other logic currently other than that

regards

**Comment by David-Desmaisons** [comment]
@jmecosta, Do you have more information regarding this issue?
Are you trying to load an html page outside of the Neutronium navigation?

**Comment by jmecosta** [comment]
Yep the redirect is for a external page, but it kind of works but when
swapping tabs I get that crash.

**Comment by jmecosta** [comment]
I mean the redirect is in a html script, not in the xml. In xaml I point to a index.html

**Comment by David-Desmaisons** [comment]
This kind of scenario is not supported.
You may use an iframe if you need to open an "external" page inside an HTML view.
If you could provide any additional information on your scenario, it will be helpful.

**Comment by jmecosta** [comment]
I'm trying to get authentication to a external SAML provider, I notice that in a browser if Auth is done then I can use the rest api in some other server without problems. I was trying to do the same with the webcontrol.  Perhaps the iframr would work if then taken all cookies into the current window. There will be some JavaScript code making the request, I've enable that part already in the chromium process.

Do you have any ideas how this can be done?

**Comment by jmecosta** [comment]
@David-Desmaisons iframe is also not an option, since i get this message when trying to load the data

refuse to load "" in a frame because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self'

**Comment by David-Desmaisons** [comment]
@jmecosta , this is most probably linked to SOP. Please check the documentation to disable it:
[Accessing Chromium API](https://github.com/NeutroniumCore/Neutronium/blob/master/Documentation/Content/Accessing_Chromium_API.md)

**Comment by jmecosta** [comment]
I was already doing that, without much luck unfortunately.  I've pass the
disable Web security argument without much luxk

**Comment by jmecosta** [comment]
@David-Desmaisons was trying now something different, ive coded a chromium extension a la ARC cookie exchange. 

now i cannot set the cookies since i asume there is no domain. do you have a workaround for this?

**Comment by David-Desmaisons** [comment]
Hello @jmecosta , I need more detail to understand the scenario.

Neutronium is designed to build desktop application, as such identification (that may imply the use of a dedicated webservice) should take place in the C# part of the application,
HTML files are designed to be "served" from the file system.

In term of architecture, I do not understand why in your case identification take place in the embedded web pages.

It seems to me that you need more an embeded webbrowser than a HTML UI engine with binding capacities, etc....


Please clarify the big picture so I can see what can be done

**Comment by jmecosta** [comment]
basically we have a desktop app that connects to jira and collects user defects. earlier jira was allowing basic auth so everything was done in c# side.

now we are moving jira to a single sign on federated solution based on SAML 2.0. Has this is web only application, and jira it self does not provide way of using the api without going through SAML 2.0 then i was thinking of using neutronium as the web app to run all the rest requests after autheticating via SAML. but seems this is really unsupported.

i am now working around by seting up a proxy application that uses a service account to to collect the application. Bit workaround but works. hopefully in future jira will provide the tokens to access the api.

anyway thanks for your help
