### ISSUE TITLE
System.ObjectDisposedException

### ISSUE THREAD

**Issue by o2genum** [NeutroniumCore/Neutronium#42]
Got some Neutronium-related exceptions collected from the users.

This exception has 7 occurences across 300+ beta users.

```
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'CfxCommandLine'.
   at Chromium.CfxLibraryBase.get_NativePtr()
   at Chromium.CfxCommandLine.AppendSwitchWithValue(String name, String value)
   at Chromium.Remote.RemoteService.OnBeforeChildProcessLaunch(Object sender, CfxOnBeforeChildProcessLaunchEventArgs e)
   at Chromium.CfxBrowserProcessHandler.on_before_child_process_launch(IntPtr gcHandlePtr, IntPtr command_line, Int32& command_line_release)
```

This exception has 1 occurence across 300+ beta users.

```
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'CfxBrowser'.
   at Chromium.CfxLibraryBase.get_NativePtr()
   at Chromium.CfxBrowser.get_MainFrame()
   at Chromium.WebBrowser.ChromiumWebBrowser.AfterSetBrowserTasks(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

**Comment by David-Desmaisons** [comment]
I have never seen exception like this. Do you have more information regarding the corresponding scanerio?
Do these exception appear when launching the application?

**Comment by David-Desmaisons** [comment]
@o2genum , I create an issue [here](https://bitbucket.org/chromiumfx/chromiumfx/issues/160/systemobjectdisposedexception-on-some) on the chromiumFx repository as it is Cfx related.

**Comment by o2genum** [comment]
This seems to happen on application/system shutdown.

This is probably related to my app logic, something must be getting updated in the ViewModel when everything's already got disposed. I'll close this issue when I've got it fixed.

**Comment by David-Desmaisons** [comment]
Good to hear that this linked to app lifecycle and probablity quite easily fixable.
How was customer feedback globally?

**Comment by o2genum** [comment]
It's good! I'll post the app info for reference when it's out of beta and is publicly available.
