### ISSUE TITLE
hot-reload crashing

### ISSUE THREAD

**Issue by fizxmike** [NeutroniumCore/Neutronium#68]
Here is the output from the debug window, not sure if there is something about my ViewModel that is causing this:
```
Neutronium - Browser Log: Message: [WDS] App updated. Recompiling..., source: http://localhost:9000/dist/build.js, line number: 4335, page: http://localhost:9000/index.html
Neutronium - Browser Log: Message: [WDS] App updated. Recompiling..., source: http://localhost:9000/dist/build.js, line number: 4335, page: http://localhost:9000/index.html
Neutronium - Browser Log: Message: [WDS] App hot update..., source: http://localhost:9000/dist/build.js, line number: 4467, page: http://localhost:9000/index.html
Neutronium - Browser Log: Message: [HMR] Checking for updates on the server..., source: http://localhost:9000/dist/build.js, line number: 4549, page: http://localhost:9000/index.html
Neutronium - Browser Log: Message: Uncaught RangeError: Maximum call stack size exceeded, source: http://localhost:9000/dist/build.js, line number: 889, page: http://localhost:9000/index.html
Neutronium - Browser Log: Message: [HMR] Cannot apply update. Need to do a full reload!, source: http://localhost:9000/dist/build.js, line number: 4537, page: http://localhost:9000/index.html
Neutronium - Browser Log: Message: [HMR] Error: Aborted because 99 is not accepted
Update propagation: 99
    at hotApply (http://localhost:9000/dist/build.js:1066:30)
    at hotUpdateDownloaded (http://localhost:9000/dist/build.js:919:13)
    at hotAddUpdateChunk (http://localhost:9000/dist/build.js:899:13)
    at webpackHotUpdateCallback (http://localhost:9000/dist/build.js:644:12)
    at http://localhost:9000/dist/0.5a86d9b86cd811beb06b.hot-update.js:1:1, source: http://localhost:9000/dist/build.js, line number: 4538, page: http://localhost:9000/index.html
Neutronium - Error - Page changes detected reloading bindings.
Neutronium - Browser Log: Message: [HMR] Waiting for update signal from WDS..., source: http://localhost:9000/dist/build.js, line number: 4553, page: http://localhost:9000/index.html#/Patient/0/0/0
The program '[11256] OneSign.exe' has exited with code 1 (0x1).
The program '[11256] OneSign.exe: Program Trace' has exited with code 0 (0x0).

```

**Comment by fizxmike** [comment]
Does any thread context switching happen on the re-bind event? I'm using an API behind one of my ViewModels that expects single-thread behavior. If that is the case, I will need to isolate it better. Meanwhile I will try to catch the error... (I was running in Debug mode, so maybe an un-managed exception is thrown down in one of my APIs killing the whole process.)

**Comment by David-Desmaisons** [comment]
I will check if the rebinding is always performed on the UI thread, if not I will dispatch it.

**Comment by David-Desmaisons** [comment]
I just check, the event is already dispatched on the UI thread.

**Comment by David-Desmaisons** [comment]
@fizxmike Any feeback on this one?
